model_list:
  # RUN POD VLLM Models
  - model_name: runpod-vllm-mistral
    litellm_params:
      model: hosted_vllm/mistralai/Mistral-7B-Instruct-v0.3
      api_base: https://gnfzhaynntlve2-8080.proxy.runpod.net/v1
      api_key: none
  # OPENAI Models
  - model_name: oai-gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano
      api_key: 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
  - model_name: oai-text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: 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
  # Anthropic Models
  - model_name: anthropic-claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: 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
  # Ollama Models
  - model_name: ollama-mistral
    litellm_params:
      model: ollama/mistral
      api_base: http://192.168.2.114:11434
      api_key: none
  - model_name: ollama-llama-vision
    litellm_params:
      model: ollama/llama3.2-vision
      api_base: http://192.168.2.114:11434
      api_key: none
