[project]
name = "3-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "langchain[openai]>=1.0.2",
    "python-dotenv>=1.1.0",
]
